return require('packer').startup(function(use)
	use('wbthomason/packer.nvim')
	use(require('hedgey.plugins.colorschemes'))
    use(require('hedgey.plugins.telescope-fzf-native'))
    use(require('hedgey.plugins.telescope'))
    use(require('hedgey.plugins.harpoon'))
    use(require('hedgey.plugins.surround'))
    use(require('hedgey.plugins.comment'))
    use(require('hedgey.plugins.vim-fugitive'))
    use(require('hedgey.plugins.lsp'))
    use(require('hedgey.plugins.zenmode'))
    use(require('hedgey.plugins.lualine'))
    use(require('hedgey.plugins.treesitter'))
    use(require('hedgey.plugins.autopairs'))
end)
